# Generated by Django 3.1.2 on 2020-10-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('program', models.CharField(blank=True, max_length=5)),
                ('intake_semester', models.CharField(blank=True, max_length=15)),
                ('mobile_no', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('current_address', models.CharField(blank=True, max_length=200)),
                ('permanent_address', models.CharField(blank=True, max_length=200)),
                ('Degree_Duration', models.CharField(blank=True, max_length=3)),
                ('max_semester', models.CharField(blank=True, max_length=15)),
                ('Image', models.ImageField(upload_to='students_image/uploads')),
            ],
        ),
    ]
