# Generated by Django 3.1.2 on 2020-10-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='URlS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
