# Generated by Django 3.1.2 on 2020-10-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='season',
            field=models.CharField(max_length=30),
        ),
    ]
