# Generated by Django 3.1.2 on 2020-10-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20201030_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
