# Generated by Django 3.1.2 on 2020-10-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_auto_20201031_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='intake_semester',
            new_name='year',
        ),
        migrations.AddField(
            model_name='user',
            name='season',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
