# Generated by Django 3.1.2 on 2020-10-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_auto_20201031_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_upload',
            name='Term_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.terms'),
        ),
    ]
