# Generated by Django 3.1.2 on 2020-10-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_upload',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.subjects'),
        ),
    ]
